"""baseline del esquema existente

Revision ID: eca1f1c0b41a
Revises: 
Create Date: 2026-07-25 19:56:12.993178
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eca1f1c0b41a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wsp_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.Text(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('wa_message_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('media_width', sa.Integer(), nullable=True),
    sa.Column('media_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wsp_messages_chat_cursor', 'wsp_messages', ['chat_id', sa.literal_column('sent_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('builder_mode', sa.Text(), server_default='simple', nullable=False),
    sa.Column('flow_definition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('published_flow_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delay_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_executions_per_hour', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_automation_rules_builder_mode', 'automation_rules', ['builder_mode', 'is_active'], unique=False)
    op.create_index('idx_automation_rules_trigger_active', 'automation_rules', ['trigger_type', 'is_active'], unique=False)
    op.create_table('lead_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_lead_tags_created_by', 'lead_tags', ['created_by'], unique=False)
    op.create_index('uq_lead_tags_name_lower', 'lead_tags', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('leads',
    sa.Column('remote_jid', sa.Text(), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('servicio_interes', sa.Text(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('vendedor', sa.Text(), nullable=True),
    sa.Column('origen', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', postgresql.ENUM('nuevo', 'en_diagnostico', 'calificado', 'oferta_presentada', 'en_objecion', 'agendado', 'cliente_activo', 'postventa', 'en_seguimiento', 'en_nutricion', 'perdido', 'descalificado', 'baja', name='lead_estado'), server_default='nuevo', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_suggestion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('con_especialista', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('razon_perdido', sa.Text(), nullable=True),
    sa.Column('fecha_recontacto', sa.Date(), nullable=True),
    sa.Column('contador_noshow', sa.SmallInteger(), nullable=True),
    sa.Column('proxima_cita', sa.DateTime(timezone=True), nullable=True),
    sa.Column('toques_seguimiento', sa.SmallInteger(), nullable=True),
    sa.Column('fecha_ultimo_toque', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('remote_jid')
    )
    op.create_index('idx_leads_vendedor_id', 'leads', ['vendedor_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_url')
    )
    op.create_index('idx_media_assets_content_type', 'media_assets', ['content_type'], unique=False)
    op.create_index('idx_media_assets_created_at', 'media_assets', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('shortcut', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default='global', nullable=False),
    sa.Column('template_type', sa.Text(), server_default='internal', nullable=False),
    sa.Column('official_name', sa.Text(), nullable=True),
    sa.Column('official_language', sa.Text(), nullable=True),
    sa.Column('official_category', sa.Text(), nullable=True),
    sa.Column('official_status', sa.Text(), nullable=True),
    sa.Column('official_parameter_values', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('interactive_type', sa.Text(), server_default='none', nullable=False),
    sa.Column('interactive_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_templates_active_category', 'message_templates', ['is_active', 'category'], unique=False)
    op.create_index('idx_message_templates_interactive_type', 'message_templates', ['interactive_type', 'is_active'], unique=False)
    op.create_index('idx_message_templates_type_status', 'message_templates', ['template_type', 'official_status', 'is_active'], unique=False)
    op.create_index('uq_templates_global_shortcut_lower', 'message_templates', [sa.literal_column('lower(shortcut)')], unique=True, postgresql_where=sa.text("visibility = 'global' AND shortcut IS NOT NULL"))
    op.create_index('uq_templates_personal_shortcut_owner', 'message_templates', ['created_by_user_id', sa.literal_column('lower(shortcut)')], unique=True, postgresql_where=sa.text("visibility = 'personal' AND shortcut IS NOT NULL"))
    op.create_table('automation_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('event_key', sa.Text(), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='scheduled', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_results', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('flow_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_automation_executions_due', 'automation_executions', ['status', 'scheduled_for'], unique=False)
    op.create_index('idx_automation_executions_lead_created', 'automation_executions', ['lead_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_automation_executions_rule_created', 'automation_executions', ['rule_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_automation_execution_rule_event', 'automation_executions', ['rule_id', 'event_key'], unique=True)
    op.create_table('automation_flow_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_automation_flow_versions_rule_version', 'automation_flow_versions', ['rule_id', 'version'], unique=True)
    op.create_table('lead_activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_activity_actor_user', 'lead_activity', ['actor_user_id'], unique=False)
    op.create_index('idx_lead_activity_lead_created', 'lead_activity', ['lead_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_notes_lead_created', 'lead_notes', ['lead_id', 'created_at', 'id'], unique=False)
    op.create_table('lead_tag_assignments',
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['lead_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', 'tag_id')
    )
    op.create_index('idx_lead_tag_assignments_assigned_by', 'lead_tag_assignments', ['assigned_by'], unique=False)
    op.create_index('idx_lead_tag_assignments_tag_lead', 'lead_tag_assignments', ['tag_id', 'lead_id'], unique=False)
    op.create_table('lead_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_tasks_assignee_status_due', 'lead_tasks', ['assigned_user_id', 'status', 'due_at'], unique=False)
    op.create_index('idx_lead_tasks_lead_status_due', 'lead_tasks', ['lead_id', 'status', 'due_at'], unique=False)
    op.create_table('message_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['wsp_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_message_outbox_chat_order', 'message_outbox', ['chat_id', 'id'], unique=False)
    op.create_index('idx_message_outbox_pending', 'message_outbox', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_table('scheduled_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('queued_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queued_message_id'], ['wsp_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queued_message_id')
    )
    op.create_index('idx_scheduled_messages_due', 'scheduled_messages', ['status', 'scheduled_at', 'id'], unique=False)
    op.create_index('idx_scheduled_messages_lead', 'scheduled_messages', ['lead_id', sa.literal_column('scheduled_at DESC')], unique=False)
    op.create_table('template_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('library_asset_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_attachments_template_position', 'template_attachments', ['template_id', 'position'], unique=False)
    op.create_table('template_user_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'template_id')
    )
    op.create_index('idx_template_user_state_recent', 'template_user_state', ['user_id', sa.literal_column('last_used_at DESC')], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.remote_jid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_notifications_lead', 'user_notifications', ['lead_id'], unique=False)
    op.create_index('idx_user_notifications_user_created', 'user_notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_notifications_user_read', 'user_notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('lead_note_mentions',
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['lead_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'user_id')
    )
    op.create_index('idx_lead_note_mentions_user', 'lead_note_mentions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    _apply_startup_ddl()


def _apply_startup_ddl() -> None:
    """Lo que hasta ahora creaba el arranque de la aplicación.

    models.py no declara estos objetos, asi que autogenerate no los ve. Se
    reproducen aqui para que una instalacion desde cero quede igual que
    produccion. Verificado comparando ambos esquemas: sin esto faltarian
    exactamente estos indices y restricciones.

    No se incluyen los indices que mantiene n8n sobre `leads` y
    `wsp_messages` (idx_leads_estado, idx_leads_ultimo_mensaje_at,
    idx_wsp_messages_chat_id y demas): son de columnas que este proyecto ni
    siquiera declara, y su ciclo de vida pertenece a ese flujo.
    """
    # La FK leads.vendedor_id -> users.id no se añade aquí: la definición de
    # la tabla ya la crea, como `leads_vendedor_id_fkey`. En producción se
    # llama `fk_leads_vendedor_id_users` porque la creó el arranque con nombre
    # explícito; es la misma restricción y el código acepta ambos nombres.
    #
    # sender NOT NULL: equivalente a migrations/019. Las consultas del CRM
    # asumen 'cliente' o 'vendedor' y un NULL rompia el hilo.
    op.execute(
        "ALTER TABLE wsp_messages ADD CONSTRAINT wsp_messages_sender_check "
        "CHECK (sender IN ('cliente', 'vendedor'))"
    )
    op.execute("CREATE INDEX idx_wsp_messages_sent_at ON wsp_messages(sent_at)")
    op.execute(
        "CREATE INDEX idx_wsp_messages_wa_message_id ON wsp_messages(wa_message_id) "
        "WHERE wa_message_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX idx_lead_tasks_due_pending ON lead_tasks(due_at) "
        "WHERE status = 'pending'"
    )
    op.execute(
        "CREATE INDEX idx_lead_tasks_pending_reminder ON lead_tasks(remind_at) "
        "WHERE status = 'pending' AND reminder_sent_at IS NULL"
    )
    op.execute(
        "CREATE INDEX idx_template_attachments_library_asset "
        "ON template_attachments(library_asset_id)"
    )
    _apply_search_indexes()


def _apply_search_indexes() -> None:
    """Busqueda insensible a acentos.

    Crear extensiones exige permisos que un usuario de una base gestionada no
    siempre tiene. Como la aplicacion ya degrada a ILIKE cuando f_unaccent no
    existe (ver set_unaccent_enabled en db_service), aqui se avisa y se sigue
    en vez de dejar la migracion a medias: quedarse sin acentos es peor que
    quedarse sin base de datos, pero mucho mejor que un despliegue bloqueado.
    """
    connection = op.get_bind()
    try:
        with connection.begin_nested():
            connection.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS unaccent")
            connection.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS pg_trgm")
            connection.exec_driver_sql(
                "CREATE OR REPLACE FUNCTION f_unaccent(text) RETURNS text AS "
                "$$ SELECT public.unaccent('public.unaccent', $1) $$ "
                "LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT"
            )
            connection.exec_driver_sql(
                "CREATE INDEX idx_wsp_messages_content_trgm "
                "ON wsp_messages USING gin (f_unaccent(content) gin_trgm_ops)"
            )
            connection.exec_driver_sql(
                "CREATE INDEX idx_leads_nombre_trgm "
                "ON leads USING gin (f_unaccent(nombre) gin_trgm_ops)"
            )
    except Exception as exc:  # noqa: BLE001 - degradar, no bloquear
        print(
            "AVISO: no se pudieron crear las extensiones de busqueda "
            f"({type(exc).__name__}). La busqueda sera sensible a acentos. "
            "Aplicar backend/migrations/020_search_unaccent.sql con un usuario "
            "con permisos para habilitarla."
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_note_mentions_user', table_name='lead_note_mentions')
    op.drop_table('lead_note_mentions')
    op.drop_index('idx_user_notifications_user_read', table_name='user_notifications')
    op.drop_index('idx_user_notifications_user_created', table_name='user_notifications')
    op.drop_index('idx_user_notifications_lead', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('idx_template_user_state_recent', table_name='template_user_state')
    op.drop_table('template_user_state')
    op.drop_index('idx_template_attachments_template_position', table_name='template_attachments')
    op.drop_table('template_attachments')
    op.drop_index('idx_scheduled_messages_lead', table_name='scheduled_messages')
    op.drop_index('idx_scheduled_messages_due', table_name='scheduled_messages')
    op.drop_table('scheduled_messages')
    op.drop_index('idx_message_outbox_pending', table_name='message_outbox')
    op.drop_index('idx_message_outbox_chat_order', table_name='message_outbox')
    op.drop_table('message_outbox')
    op.drop_index('idx_lead_tasks_lead_status_due', table_name='lead_tasks')
    op.drop_index('idx_lead_tasks_assignee_status_due', table_name='lead_tasks')
    op.drop_table('lead_tasks')
    op.drop_index('idx_lead_tag_assignments_tag_lead', table_name='lead_tag_assignments')
    op.drop_index('idx_lead_tag_assignments_assigned_by', table_name='lead_tag_assignments')
    op.drop_table('lead_tag_assignments')
    op.drop_index('idx_lead_notes_lead_created', table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index('idx_lead_activity_lead_created', table_name='lead_activity')
    op.drop_index('idx_lead_activity_actor_user', table_name='lead_activity')
    op.drop_table('lead_activity')
    op.drop_index('uq_automation_flow_versions_rule_version', table_name='automation_flow_versions')
    op.drop_table('automation_flow_versions')
    op.drop_index('uq_automation_execution_rule_event', table_name='automation_executions')
    op.drop_index('idx_automation_executions_rule_created', table_name='automation_executions')
    op.drop_index('idx_automation_executions_lead_created', table_name='automation_executions')
    op.drop_index('idx_automation_executions_due', table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index('uq_templates_personal_shortcut_owner', table_name='message_templates', postgresql_where=sa.text("visibility = 'personal' AND shortcut IS NOT NULL"))
    op.drop_index('uq_templates_global_shortcut_lower', table_name='message_templates', postgresql_where=sa.text("visibility = 'global' AND shortcut IS NOT NULL"))
    op.drop_index('idx_message_templates_type_status', table_name='message_templates')
    op.drop_index('idx_message_templates_interactive_type', table_name='message_templates')
    op.drop_index('idx_message_templates_active_category', table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index('idx_media_assets_created_at', table_name='media_assets')
    op.drop_index('idx_media_assets_content_type', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('idx_leads_vendedor_id', table_name='leads')
    op.drop_table('leads')
    op.drop_index('uq_lead_tags_name_lower', table_name='lead_tags')
    op.drop_index('idx_lead_tags_created_by', table_name='lead_tags')
    op.drop_table('lead_tags')
    op.drop_index('idx_automation_rules_trigger_active', table_name='automation_rules')
    op.drop_index('idx_automation_rules_builder_mode', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index('idx_wsp_messages_chat_cursor', table_name='wsp_messages')
    op.drop_table('wsp_messages')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
